// <auto-generated />
using System;
using System.Collections.Generic;
using GrowSphere.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GrowSphere.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250520092030_AddUserProject")]
    partial class AddUserProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GrowSphere.Domain.Models.CategoryModel.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.ComplexProperty<Dictionary<string, object>>("Title", "GrowSphere.Domain.Models.CategoryModel.Category.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("title");
                        });

                    b.HasKey("Id")
                        .HasName("pK_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.IssueModel.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignerUserId");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("complete_date");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("projectId");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "GrowSphere.Domain.Models.IssueModel.Issue.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Picture", "GrowSphere.Domain.Models.IssueModel.Issue.Picture#Picture", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("MimeType")
                                .HasColumnType("text")
                                .HasColumnName("mime_type");

                            b1.Property<string>("Path")
                                .HasColumnType("text")
                                .HasColumnName("picture_path");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "GrowSphere.Domain.Models.IssueModel.Issue.Status#IssueStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "GrowSphere.Domain.Models.IssueModel.Issue.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("title");
                        });

                    b.HasKey("Id")
                        .HasName("pK_issue");

                    b.HasIndex("AssignerUserId")
                        .HasDatabaseName("iX_issue_assignerUserId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("iX_issue_projectId");

                    b.ToTable("issue", (string)null);
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.ProjectModel.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.ComplexProperty<Dictionary<string, object>>("Description", "GrowSphere.Domain.Models.ProjectModel.Project.Description#Description", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Status", "GrowSphere.Domain.Models.ProjectModel.Project.Status#ProjectStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("status");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Title", "GrowSphere.Domain.Models.ProjectModel.Project.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("title");
                        });

                    b.HasKey("Id")
                        .HasName("pK_project");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("iX_project_categoryId");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.SkillModel.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.ComplexProperty<Dictionary<string, object>>("Title", "GrowSphere.Domain.Models.SkillModel.Skill.Title#Title", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("title");
                        });

                    b.HasKey("Id")
                        .HasName("pK_skill");

                    b.ToTable("skill", (string)null);
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.UserModel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.ComplexProperty<Dictionary<string, object>>("Bio", "GrowSphere.Domain.Models.UserModel.User.Bio#Bio", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("bio");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "GrowSphere.Domain.Models.UserModel.User.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "GrowSphere.Domain.Models.UserModel.User.Name#UserName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("username");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("ProfilePicture", "GrowSphere.Domain.Models.UserModel.User.ProfilePicture#Picture", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("MimeType")
                                .HasColumnType("text")
                                .HasColumnName("mime_type");

                            b1.Property<string>("Path")
                                .HasColumnType("text")
                                .HasColumnName("path");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("UserStatus", "GrowSphere.Domain.Models.UserModel.User.UserStatus#UserStatus", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .HasColumnType("text")
                                .HasColumnName("status");
                        });

                    b.HasKey("Id")
                        .HasName("pK_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.UserModel.UserProject", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.HasKey("UserId", "ProjectId")
                        .HasName("pK_user_project");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("iX_user_project_projectId");

                    b.ToTable("user_project", (string)null);
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.UserModel.UserSkill", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("UserId", "SkillId")
                        .HasName("pK_user_skill");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("iX_user_skill_skillId");

                    b.ToTable("user_skill", (string)null);
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.IssueModel.Issue", b =>
                {
                    b.HasOne("GrowSphere.Domain.Models.UserModel.User", "AssignerUser")
                        .WithMany()
                        .HasForeignKey("AssignerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_issue_user_assignerUserId");

                    b.HasOne("GrowSphere.Domain.Models.ProjectModel.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_issue_project_projectId");

                    b.Navigation("AssignerUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.ProjectModel.Project", b =>
                {
                    b.HasOne("GrowSphere.Domain.Models.CategoryModel.Category", "Category")
                        .WithMany("Projects")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_project_category_categoryId");

                    b.OwnsOne("GrowSphere.Domain.Models.ProjectModel.Members", "Members", b1 =>
                        {
                            b1.Property<Guid>("ProjectId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.HasKey("ProjectId");

                            b1.ToTable("project");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId")
                                .HasConstraintName("fK_project_project_id");

                            b1.OwnsMany("GrowSphere.Domain.Models.ProjectModel.Member", "MembersList", b2 =>
                                {
                                    b2.Property<Guid>("project_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("project_id");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasColumnName("id");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("Role")
                                        .HasColumnType("integer")
                                        .HasColumnName("role");

                                    b2.Property<Guid>("user_id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("user_id");

                                    b2.HasKey("project_id", "Id")
                                        .HasName("pK_member");

                                    b2.HasIndex("user_id")
                                        .HasDatabaseName("iX_member_user_id");

                                    b2.ToTable("member", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("project_id")
                                        .HasConstraintName("fK_member_project_project_id");

                                    b2.HasOne("GrowSphere.Domain.Models.UserModel.User", "User")
                                        .WithMany()
                                        .HasForeignKey("user_id")
                                        .OnDelete(DeleteBehavior.Cascade)
                                        .IsRequired()
                                        .HasConstraintName("fK_member_user_user_id");

                                    b2.Navigation("User");
                                });

                            b1.Navigation("MembersList");
                        });

                    b.Navigation("Category");

                    b.Navigation("Members")
                        .IsRequired();
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.UserModel.UserProject", b =>
                {
                    b.HasOne("GrowSphere.Domain.Models.ProjectModel.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_user_project_project_projectId");

                    b.HasOne("GrowSphere.Domain.Models.UserModel.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fK_user_project_user_userId");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.UserModel.UserSkill", b =>
                {
                    b.HasOne("GrowSphere.Domain.Models.SkillModel.Skill", "Skill")
                        .WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_user_skill_skill_skillId");

                    b.HasOne("GrowSphere.Domain.Models.UserModel.User", "User")
                        .WithMany("Skills")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fK_user_skill_user_userId");

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.CategoryModel.Category", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.ProjectModel.Project", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("GrowSphere.Domain.Models.UserModel.User", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
